title: "Prodigy recipes for document processing and layout understanding"

directories:
  - "assets"
  - "dataset"
  - "model"

vars:
  dataset_name: funsd

assets:
  - dest: "assets/${vars.dataset_name}.zip"
    description: "FUNSD dataset - noisy scanned documents for layout understanding"
    url: https://guillaumejaume.github.io/FUNSD/dataset.zip

workflows:
  clean-all:
    - "clean-db"
    - "clean"

commands:
  - name: "install"
    help: "Install dependencies"
    script:
      - "pip install --user -r requirements.txt"

  - name: "hydrate-db"
    help: "Hydrate the Prodigy database with annotated data from FUNSD"
    script:
      - "python -m scripts.preprocess assets/${vars.dataset_name}.zip dataset/"
      - "python -m prodigy db-in-image ${vars.dataset_name} -F scripts/recipes/loaders.py"

  - name: "review"
    help: "Review hydrated annotations"
    script:
      - "python -m prodigy db-out ${vars.dataset_name} dataset"
      - >-
        python -m prodigy image.manual 
        ${vars.dataset_name}-debug 
        dataset/${vars.dataset_name}.jsonl 
        --loader jsonl 
        --label question,answer,header,other

  - name: "train"
    help: "Train FUNSD model"
    script:
      - >-
        python -m prodigy train-image ${vars.dataset_name} model/
        -F scripts/recipes/train.py --verbose --eval

  - name: "clean-db"
    help: "Drop all generated Prodigy datasets"
    script:
      - "prodigy drop ${vars.dataset_name}"
      - "prodigy drop ${vars.dataset_name}-debug"

  - name: "clean"
    help: "Clean all intermediary files"
    script:
      - "sh -c 'rm -rf assets/*'"
      - "sh -c 'rm -rf dataset/*'"
