title: "Prodigy recipes for document processing and layout understanding"

directories:
  - "assets"
  - "images"

assets:
  - dest: "assets/funsd.zip"
    description: "FUNSD dataset - noisy scanned documents for layout understanding"
    url: https://guillaumejaume.github.io/FUNSD/dataset.zip
